# =============================================================================
# AQI FEATURE ENGINEERING PIPELINE
# SAFE TIME-SERIES FEATURE STORE PIPELINE
# NO DATA LEAKAGE
# READY FOR SUPABASE FEATURE STORE
# =============================================================================

# =============================================================================
# IMPORTS
# =============================================================================

import os
import numpy as np
import pandas as pd
from supabase import create_client

# =============================================================================
# INITIALIZE SUPABASE CLIENT
# =============================================================================
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

os.makedirs("data/processed", exist_ok=True)

# =============================================================================
# LOAD FRESH RAW HOUR AND PULL HISTORICAL CONTEXT FROM SUPABASE
# =============================================================================
# 1. Load the brand new row(s) generated by your ingestion script
new_raw_df = pd.read_csv("data/raw/karachi_aqi_historical.csv")
new_raw_df["timestamp"] = pd.to_datetime(new_raw_df["timestamp"])

print(f"Loaded {len(new_raw_df)} new raw rows from ingestion.")

# 2. Pull down the last 5 days (120 hours) of features from your production database 
# to act as a buffer context for calculating lag/rolling features.
print("Fetching past 120 hours of data from Supabase for feature calculations...")
response = (
    supabase.table("aqi_features")
    .select("*")
    .order("timestamp", ascending=False)
    .limit(120)
    .execute()
)

if response.data:
    df_context = pd.DataFrame(response.data)
    df_context["timestamp"] = pd.to_datetime(df_context["timestamp"])
    
    # Isolate only the core base metrics from your historical records
    base_cols = ["timestamp", "pm2_5", "us_aqi", "temperature", "humidity", 
                 "pressure", "wind_speed", "carbon_monoxide", "nitrogen_dioxide", 
                 "sulphur_dioxide", "ozone", "pm10"]
    # Filter columns to only what exists in your database table schema
    available_cols = [c for c in base_cols if c in df_context.columns]
    df_context = df_context[available_cols]

    # Combine historical context with your fresh incoming API rows
    raw_df = pd.concat([df_context, new_raw_df], ignore_index=True)
    # Deduplicate in case the new data overlaps with what is already recorded
    raw_df = raw_df.drop_duplicates(subset=["timestamp"]).sort_values("timestamp").reset_index(drop=True)
else:
    print("⚠️ Supabase 'aqi_features' table is empty. Running with raw local data only.")
    raw_df = new_raw_df.copy()

print(f"Total contextual dataset size for engineering: {raw_df.shape}")

# =============================================================================
# FEATURE ENGINEERING FUNCTION (Kept intact exactly as you wrote it)
# =============================================================================
def engineer_aqi_features(df):
    df = df.copy()
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values("timestamp").reset_index(drop=True)

    essential_cols = ["pm2_5", "us_aqi"]
    df = df.dropna(subset=essential_cols)

    df["pm25_log"] = np.log1p(df["pm2_5"])

    # Time features
    df["hour_of_day"] = df["timestamp"].dt.hour
    df["day_of_week"] = df["timestamp"].dt.dayofweek
    df["month_of_year"] = df["timestamp"].dt.month
    df["day_of_month"] = df["timestamp"].dt.day
    df["week_of_year"] = df["timestamp"].dt.isocalendar().week.astype(int)
    df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

    def get_season(month):
        if month in [12, 1, 2]: return 0
        elif month in [3, 4, 5]: return 1
        elif month in [6, 7, 8]: return 2
        else: return 3

    df["season"] = df["month_of_year"].apply(get_season)

    # Cyclical Features
    df["hour_sin"] = np.sin(2 * np.pi * df["hour_of_day"] / 24)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour_of_day"] / 24)
    df["day_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7)
    df["day_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7)
    df["month_sin"] = np.sin(2 * np.pi * df["month_of_year"] / 12)
    df["month_cos"] = np.cos(2 * np.pi * df["month_of_year"] / 12)

    # Lag & Rolling Features
    df["aqi_lag_1h"] = df["us_aqi"].shift(1)
    df["aqi_lag_6h"] = df["us_aqi"].shift(6)
    df["aqi_lag_24h"] = df["us_aqi"].shift(24)

    df["aqi_rolling_avg_6h"] = df["us_aqi"].shift(1).rolling(6).mean()
    df["aqi_rolling_avg_24h"] = df["us_aqi"].shift(1).rolling(24).mean()
    df["aqi_change_rate_24h"] = df["us_aqi"].diff(24)

    for lag in [1, 2, 3, 6, 12, 24, 48]:
        df[f"pm25_lag_{lag}"] = df["pm2_5"].shift(lag)

    if "pm10" in df.columns:
        for lag in [6, 24]:
            df[f"pm10_lag_{lag}"] = df["pm10"].shift(lag)
        df["pm_ratio"] = df["pm2_5"] / (df["pm10"] + 1e-6)

    for w in [3, 6, 12, 24]:
        df[f"pm25_roll_mean_{w}"] = df["pm2_5"].shift(1).rolling(w).mean()

    for w in [6, 12, 24]:
        df[f"pm25_roll_std_{w}"] = df["pm2_5"].shift(1).rolling(w).std()

    for w in [6, 24]:
        df[f"pm25_roll_min_{w}"] = df["pm2_5"].shift(1).rolling(w).min()

    for w in [3, 6, 24]:
        df[f"pm25_roll_max_{w}"] = df["pm2_5"].shift(1).rolling(w).max()

    df["pm25_median_24"] = df["pm2_5"].shift(1).rolling(24).median()

    for span in [3, 6, 12, 24]:
        df[f"pm25_ema_{span}"] = df["pm2_5"].shift(1).ewm(span=span, adjust=False).mean()

    df["pm25_ewm_std_24"] = df["pm2_5"].shift(1).ewm(span=24).std()
    df["pm25_volatility_24"] = df["pm2_5"].shift(1).rolling(24).std()
    df["pm25_cumulative_24"] = df["pm2_5"].shift(1).rolling(24).sum()

    df["pollution_spike"] = (df["pm2_5"] > (df["pm2_5"].shift(1).rolling(24).mean() * 1.5)).astype(int)
    df["high_pollution_flag"] = (df["pm2_5"] > 35).astype(int)

    # Weather & Chemical Features
    weather_cols = ["temperature", "humidity", "pressure", "wind_speed", 
                    "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone"]
    for col in weather_cols:
        if col in df.columns:
            df[f"{col}_lag_6"] = df[col].shift(6)
            df[f"{col}_roll_mean_24"] = df[col].shift(1).rolling(24).mean()

    # Targets (Shifting back to capture upcoming intervals)
    df["target_24h"] = df["pm2_5"].shift(-24)
    df["target_48h"] = df["pm2_5"].shift(-48)
    df["target_72h"] = df["pm2_5"].shift(-72)

    df = df.replace([np.inf, -np.inf], np.nan)
    
    # Drop rows that don't have enough past lookback context
    df = df.iloc[48:].reset_index(drop=True)
    return df

# =============================================================================
# GENERATE AND ISOLATE ONLY THE NEW UPCOMING RUN ROWS
# =============================================================================
df_features = engineer_aqi_features(raw_df)

# Filter the engineered dataframe down so it only contains the hours 
# matching the new timestamps we fetched during this specific action execution.
df_final = df_features[df_features["timestamp"].isin(new_raw_df["timestamp"])].reset_index(drop=True)

# Safety Fallback: If filtering strips too much context, keep the last few hours
if df_final.empty:
    print("⚠️ Target filtering resulted in an empty dataframe. Falling back to tail(72).")
    df_final = df_features.tail(72).reset_index(drop=True)

print("=" * 70)
print("FEATURE ENGINEERING COMPLETED")
print("=" * 70)
print(f"Final Output Shape for Ingestion: {df_final.shape}")

# Ensure timestamps are strictly normalized to standardized string format before saving
df_final["timestamp"] = pd.to_datetime(df_final["timestamp"], utc=True).dt.strftime("%Y-%m-%dT%H:%M:%SZ")

# Save back to CSV so 'src/upload_to_supabase.py' can pick it up smoothly
df_final.to_csv("data/processed/aqi_feature_store.csv", index=False)
print("\n✅ Cleaned and engineered feature store CSV saved successfully.")