name: Daily Model Retraining

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  retrain_pipeline:

    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_REPO: ${{ secrets.DAGSHUB_REPO }}

      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Retraining Pipeline
        run: python src/retrain_pipeline.py